[[GMT]]
arch = "aarch64"
git-tree-sha1 = "b1fc398d597ba2090de6b3bbb3bc8779ee74c31b"
os = "macos"

    [[GMT.download]]
    sha256 = "eac8d4b45403c9a5f5cd280baa6253281428cbb7646383536e7c2831d54104de"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.aarch64-apple-darwin.tar.gz"
[[GMT]]
arch = "aarch64"
git-tree-sha1 = "bad9b549219cf2e63178ec819ab7c52ac7d1a7d8"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "a5e0caf8760db06f94834e5789665ccf571640db1d1bcee8b3a6bfbcebd3d41a"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.aarch64-linux-gnu.tar.gz"
[[GMT]]
arch = "i686"
git-tree-sha1 = "22c123ff04b49faca3dfdd16d6e66b869d783a15"
os = "windows"

    [[GMT.download]]
    sha256 = "b40f19734f53c0fd4dd7ec63cf6d92ece7422e3145a22c290362f2576310050f"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.i686-w64-mingw32.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "c3c0c29047592e81a43bfab972e909ff2c7e1566"
os = "macos"

    [[GMT.download]]
    sha256 = "cd85c1716a3aae28fe4ff8daab97de19c541f54711e44940437528570833c4f9"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.x86_64-apple-darwin.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "87fc2e38ee602978796ed8904c29356c8fce6462"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "6faa4215a514c0bb72b855c2fced9f73ee3d1c55a9ea97d025eb008f94fddb5e"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.x86_64-linux-gnu.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "4987080ab513a94e8a14ae2adabf1df3c6af7c3d"
os = "windows"

    [[GMT.download]]
    sha256 = "c827a53da5759ce7eec4f49fbd6846be9be31a0cdaa5024ab1c103422fda884d"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.2+0/GMT.v6.6.2.x86_64-w64-mingw32.tar.gz"
