[[GMT]]
arch = "aarch64"
git-tree-sha1 = "f76aaea1b5d25de2b1b4898bc7d0c1943cb1a1dc"
os = "macos"

    [[GMT.download]]
    sha256 = "cfd225a815885a32a5ce82e3d281f393f334242eac65b03a2da42d96e127996e"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.aarch64-apple-darwin.tar.gz"
[[GMT]]
arch = "aarch64"
git-tree-sha1 = "53db62513651ed9cc229ba94fcd331041e0b9c4e"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "a4a47c263585cffee1b350a22611831a0f53d9bedde4fc45c8517cd5f07d6d93"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.aarch64-linux-gnu.tar.gz"
[[GMT]]
arch = "i686"
git-tree-sha1 = "39c4240d6786ce3f059640001b4ab292378251cc"
os = "windows"

    [[GMT.download]]
    sha256 = "47a36e76f6abceb6fff84deab9f774dd93d77f68398f1c90e7359213a5adb882"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.i686-w64-mingw32.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "11197028c53f276f147ec52169c243315c7da7a6"
os = "macos"

    [[GMT.download]]
    sha256 = "4ba78cfff45963ba5c161b8f86ff1b2d04634c2477f46ad45ae69b22aeb2ea67"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.x86_64-apple-darwin.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "d75391f81545715e8370c57bbb4e397127ab40ca"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "834bb2feb56f838925555334b9eb4f0e03ff5a70e4c6c746a2794aea69d83f48"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.x86_64-linux-gnu.tar.gz"
[[GMT]]
arch = "x86_64"
git-tree-sha1 = "452822307a54346473d9001ed15b5c3f947fa8b8"
os = "windows"

    [[GMT.download]]
    sha256 = "6cc4db294ba1e5b5e5f8549e0cbf75f6221b39c5ad7a6749d4b4c8b7c915be56"
    url = "https://github.com/JuliaBinaryWrappers/GMT_jll.jl/releases/download/GMT-v6.6.1+0/GMT.v6.6.1.x86_64-w64-mingw32.tar.gz"
